### ISSUE TITLE
Should this project be updated to match the syntax of smart contract language in v1.4 provided by official?

### ISSUE THREAD

**Issue by lowesyang** [unicoeos/eosio.nft#7]
This version cannot be compiled with `eosio.cdt` provided by official, because some syntax and function have deprecated in latest version language. 

Should it be updated?

**Comment by jafri** [comment]
Yes, the contract needs to be updated

**Comment by unicoeos** [comment]
We are working on it! Update will be available in next days

**Comment by lowesyang** [comment]
@unicoeos That's great! Thanks for your work~

**Comment by kolkhi** [comment]
The contract is updated.
